version: '3.8'

services:
  chatbot:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ~/.kube/config:/root/.kube/config:ro
    environment:
      - JWT_SECRET_KEY=s3cr3t_k3y_1234567890
      - FLASK_ENV=production  